version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      - "MYSQL_DATABASE=db"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=me"
      - "MYSQL_PASSWORD=user"
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
